server.servlet.context-path: /api
spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:kumojin
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jackson.deserialization.ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
