name: App CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: joeykidd/gestevent-api
          tags: latest
          dockerfile: ./api/Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 17
        uses: actions/setup-node@v2
        with:
          node-version: "17.6.0"
      - run: npm ci
      - run: npm run build
      # - run: npm test
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: joeykidd/gestevent-front
          tags: latest
          dockerfile: ./front/Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  #  deploy-api:
  #  deploy-front:
